### ISSUE TITLE
Case sensitive directories in composer prevents autoloading 

### ISSUE THREAD

**Issue by Sander-Kastelein** [devbolcom/bolcom-openapi-php-client#10]
Line 17 of the composer.json file tells the autloader to look for a directory called BolCom while the directory in git is called bolcom (lowercase) this messes up autoloading on Unix systems (unaware if this problem exists on Windows).

the directory
src/bolcom/
should become
src/BolCom/

Fixing this would make the API library work out of the box for PHP developers using composer autoloading. (and help me out integrating this without changing the auto loader in my project's framework)

Thanks in advance.

-- Edit: derp wasn't thinking straight.. using lowercase would break PSR-standards.

**Comment by derkmdt** [comment]
Hi Sander, thx for the heads up!

But I already see

`"BolCom\\": "src/BolCom/",`

when I look at https://raw.githubusercontent.com/devbolcom/bolcom-openapi-php-client/master/composer.json

What version are you looking at.

Derk

**Comment by Sander-Kastelein** [comment]
Terribly sorry about that, I wrote about changing it to lowercase in the composer.json but realised it should be capitalised like it is now; i "fixed" the issue above in a hurry (wrongly), what I meant to say is the actual directory in the project is currently written in lowercase, but should be capitalised the same way as in the composer.json.

To summerise, t he composer.json is fine as I can see it, it's the actual directory name which is causing issue.

This is in the current dev-master

**Comment by derkmdt** [comment]
Thx, resolved by renaming. Wich was kind of tricky with GIT tracking it.
