### ISSUE TITLE
Unieke producten

### ISSUE THREAD

**Issue by cschalenborgh** [devbolcom/bolcom-openapi-php-client#6]
Is het ook mogelijk om 'unieke' producteren te retourneren met de API? 
Momenteel krijgen wij bij een zoekopdracht alle kleuren als een apart product terug (en soms zelfs per size!). We willen graag unieke producten in een shop-manier tonen, en dat men op onze productpagina een kleur+size kan kiezen.

Via de FTP feeds krijgen we wel unieke identifiers (Family_ID) terug dus in principe kunnen we daar mee werken. Maar 8.2gb aan FTP feeds die in theorie na 1 seconde al outdated zijn + een API werkt zoveel makkelijker. Kan dit eventueel als parameter toegevoegd worden om daarop te filteren? Of is er een andere workaround beschikbaar?

![screen shot 2015-11-25 at 12 15 41](https://cloud.githubusercontent.com/assets/10864861/11395930/6185850a-936e-11e5-9800-90a75461a9bd.png)

**Comment by derkmdt** [comment]
Hoi, dit kanaal houden we niet goed bij. Vandaar de te late reactie. Maar we hebben op dit moment geen oplossing voor jouw probleem. Maar je kan het wel als feature request sturen naar developercenter@bol.com (daarmee wil ik niet zeggen dat het ook opgepakt gaat worden).
