### ISSUE TITLE
Capitalize bolcom in src folder

### ISSUE THREAD

**Issue by marzsman** [devbolcom/bolcom-openapi-php-client#9]
We have problems loading the library with composer because the folder bolcom inside the src folder isn't correctly capitalized. It should be renamed to BolCom.
There is already a fix in a [fork](https://github.com/boukeversteegh/bolcom-openapi-php-client/commit/48b1d8071712bfc37e5eca052a284199da59f169)

Could you add this fix please?

**Comment by derkmdt** [comment]
Hi Maarten, thx for the heads up. This was already on Master. See  https://github.com/devbolcom/bolcom-openapi-php-client/blob/master/composer.json. Or are you referring to something else?

**Comment by marzsman** [comment]
Sorry for my late answer. When ran into the same issue again.

I was referring to the folder name. The casing of BolCom in the json and the namespace is not the same as the physical folder name, which is lowercase.

This gives errors on non windows systems:
`PHP Fatal error:  Class 'BolCom\\Client' not found`
